# GitHub Sponsors funding configuration
# This file enables the "Sponsor" button in the GitHub repository

# Buy Me a Coffee
custom: ['https://buymeacoffee.com/shivshankarnamdev']

# Other funding platforms (uncomment and add if you use them)
# github: [shivshankarnamdev]
# patreon: shivshankarnamdev
# ko_fi: shivshankarnamdev
# liberapay: shivshankarnamdev
# issuehunt: shivshankarnamdev
# otechie: shivshankarnamdev